trigger:
- main

pool: Hosted Agent
#  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Buildjob
    displayName: 'Run Hello world script'
    steps:
    - script: echo "Hello World"
      displayName: 'Print Hello world'

- stage: Deploy
  displayName: Deploy stage
  jobs:
  - job: Deployjob
    displayName: 'Run Deploy script'
    steps:
    - script: echo 'Deploying application'
      displayName: 'Print deploying'