trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Buildjob
    displayName: 'Run Hello world script'
    steps:
    - task: Maven@3
      inputs:
        goals: 'clean install'
      displayName: 'Build with Maven'

- stage: Deploy
  displayName: Deploy stage
  jobs:
  - job: Deployjob
    displayName: 'Run Deploy script'
    steps:
    - script: echo 'Deploying application'
      displayName: 'Print deploying'