server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  h2:
    console:
      path: /h2-console
  datasource:
    password:
    url: jdbc:h2:mem:registration
    username: h2
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true




springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha